version: "3.8"

services:
  app:
    build: .
    image: alcohollocator:nginx
    container_name: alcohollocator
    restart: unless-stopped
    # If accessing directly without a reverse proxy, expose a host port
    ports:
      - "${HOST_PORT:-8080}:80"
    # If using Nginx Proxy Manager, you can remove the 'ports' section above
    # and attach this service to the same external Docker network as NPM.
    # networks:
    #   - npm_proxy

# Uncomment if you want to attach to an external network used by NPM
# networks:
#   npm_proxy:
#     external: true
